### PR TITLE
Tools to avoid hacking zarr

### PR DESCRIPTION
**Pull request by bnlawrence**
It's annoying to have to change the Array code in the zarr core... even in a virtual python, so this code avoids that.

What I thought I'd do is subclass Array, but override the methods we want to change, but the problem with that is we'd really have to hack a lot of code to get to the instantiation of the Array instances and replace them with our new class, and simpler methods don't work (e.g. see the last option in class_play.py in this pull request, which raises an AttributeError). However that same piece of code shows the tool we are using: instance method overrides.

So what we do instead, is take an instance of a Zarr Array and replace the methods we want and then use that for our active work. No more hacking zarr core!

### CODE REVIEW

**Comment by bnlawrence** [comment]
Ok, this is now updated. Your original test is there, but I have taken the code from it and inserted it into the testRead1, and have a vanilla option there too ... vanilla works, but the current code iterating over slices does not (the slices are the right variables, but are in the wrong places).  That should only require minor fixes.  (The original hijack test only works because of the `np.sort` which is cheating :-) )

**Comment by bnlawrence** [comment]
Removed a bit of code duplication in my bit, and started to mock out the direct read bypassing fsspec ... incomplete, but my bit still works as expected (i.e. just reads the data using vanilla zarr, but via our methods).

**Comment by bnlawrence** [comment]
ok, now direct read works, though I haven't changed over to it, so when you have your bit working, we can change over, and then we have ALL the bits ready to change over to computational storage. Whoop. Whoop. Whoop.

**Comment by bnlawrence** [comment]
Ok, this is now in a state we can share on Friday! The only thing left would be to add a layer to the call stack to strip the need to use the Orthogonalndexer out in the same place as we start on processing chunks. Ideally we use the OrthogonalIndexer in the Python call stack and everything below can then be reimplemented by the storage folks without need for importing zarr.

**Comment by bnlawrence** [comment]
And that's done now too. Clean separation of concerns between zarr and storage actions.

**Review by valeriupredoi — APPROVED** [review]
brilliant work, Bryan! :beer:

**Pull request merged**
